MARKDOWN_FILE_EXTENSION = "md"
MARKDOWN_HEADING_1 = "#"

COMMIT_OPTION_MESSAGE = "-m"
COMMIT_MESSAGE_INITIAL = "Initial commit"

PUSH_OPTION_SET_UPSTREAM = "-u"

REMOTE_ORIGIN = "origin"

BRANCH_NAME_MAIN = "main"